(() => {
  const panel=document.querySelector('#auth-panel'), form=document.querySelector('#auth-form'), open=document.querySelector('#auth-open'), close=document.querySelector('#auth-close'), mode=document.querySelector('#auth-mode'), title=document.querySelector('#auth-title'), message=document.querySelector('#auth-message'), plan=document.querySelector('#auth-plan'), email=document.querySelector('#auth-email');
  const tokenKey='stataxis_access_token', accountKey='stataxis_account'; let registerMode=false;
  const readAccount=()=>{try{return JSON.parse(localStorage.getItem(accountKey)||'null')}catch(_){return null}};
  const setText=(s,v)=>{const n=document.querySelector(s);if(n)n.textContent=v};
  const isApproved=()=>{const a=readAccount();return !!(localStorage.getItem(tokenKey)&&a&&(a.is_admin||a.approval_status==='approved'))};
  const realFetch=window.fetch.bind(window);
  window.fetch=(input,init={})=>{const url=typeof input==='string'?input:input.url;if(url&&url.startsWith('/api/')&&!url.includes('/api/v1/auth/')&&!isApproved())return Promise.reject(new Error('StatAxis access requires an approved profile'));return realFetch(input,init)};
  const refresh=()=>{const a=readAccount(),ok=isApproved();plan.textContent=ok?(a.plan_name||a.plan||'SX'):(a?.approval_status==='pending'?'PENDING APPROVAL':'DEMO');email.textContent=a?.email||'Not signed in';open.textContent=ok?'Sign out':'Open Profile';open.dataset.action=ok?'logout':'signin';setText('#evaluate-status',ok?'Approved profile. Ready to use StatAxis.':a?.approval_status==='pending'?'Profile submitted. Waiting for admin approval.':'Create a profile and submit it for admin approval.');setText('#aud-status',ok?'Approved profile. Live audience intelligence is available.':'Demo data only. Create a profile and wait for admin approval to use live intelligence.')};
  const showPanel=()=>{panel.hidden=false;document.querySelector('#auth-email-input')?.focus()};
  const profileFields=`<label><span>Name</span><input name="name" type="text" required maxlength="255" autocomplete="name" placeholder="Your full name"></label><label><span>Organization email</span><input id="auth-email-input" name="email" type="email" required autocomplete="email" placeholder="you@organization.com"></label><label><span>Mobile number</span><input name="mobile" type="tel" required maxlength="32" autocomplete="tel" placeholder="+91 …"></label><label><span>Organization</span><input name="organization" type="text" required maxlength="255" placeholder="Company / newsroom / institution"></label><label><span>Purpose of use</span><textarea name="purpose_of_use" required maxlength="2000" rows="3" placeholder="Tell us how you intend to use StatAxis"></textarea></label><label><span>Select package</span><select name="requested_plan" required><option value="sx_idea">SX Idea</option><option value="sx_intelligence">SX Intelligence</option><option value="sx_analyst">SX Analyst</option><option value="sx_pro">SX Pro</option><option value="sx_corporate">SX Corporate</option><option value="sx_enterprise">SX Enterprise</option></select></label><label><span>Create password</span><input name="password" type="password" required minlength="12" autocomplete="new-password" placeholder="Minimum 12 characters"></label><button type="submit">Submit for Approval</button>`;
  const setMode=(reg)=>{registerMode=reg;title.textContent=reg?'Request a StatAxis Profile':'Sign in to StatAxis';mode.textContent=reg?'Already approved? Sign in':'Create a profile';message.textContent='';form.innerHTML=reg?profileFields:`<label><span>Organization email</span><input id="auth-email-input" name="email" type="email" required autocomplete="email" placeholder="you@organization.com"></label><label><span>Password</span><input name="password" type="password" required minlength="12" autocomplete="current-password"></label><button type="submit">Sign in</button>`};
  open?.addEventListener('click',()=>{if(open.dataset.action==='logout'){localStorage.removeItem(tokenKey);localStorage.removeItem(accountKey);refresh();window.dispatchEvent(new Event('stataxis-auth-changed'));return}setMode(false);showPanel()}); close?.addEventListener('click',()=>{panel.hidden=true}); mode?.addEventListener('click',()=>setMode(!registerMode));
  form?.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button[type="submit"]');b.disabled=true;message.textContent='';const payload=Object.fromEntries(new FormData(form).entries());try{const r=await realFetch(registerMode?'/api/v1/auth/register':'/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);if(registerMode){localStorage.removeItem(tokenKey);localStorage.setItem(accountKey,JSON.stringify(d.account));message.textContent='Application submitted. Your workspace stays locked until admin approval.';refresh()}else{localStorage.setItem(tokenKey,d.access_token);localStorage.setItem(accountKey,JSON.stringify(d.account||d.user));form.reset();panel.hidden=true;refresh();window.dispatchEvent(new Event('stataxis-auth-changed'))}}catch(err){message.textContent=err.message||'Request failed'}finally{b.disabled=false}});
  const cta=document.querySelector('.public-cta'); if(cta){const badge=document.createElement('div');badge.className='demo-banner';badge.textContent='DEMO DATA — This dashboard is a preview. Live StatAxis data requires admin-approved access.';cta.prepend(badge);const how=document.createElement('button');how.type='button';how.className='ghost-button';how.textContent='How to Use';how.addEventListener('click',()=>{window.location.href='/guide.html'});cta.querySelector('div')?.appendChild(how)}
  const style=document.createElement('style');style.textContent='.demo-banner{margin-bottom:14px;padding:10px 14px;border:1px solid rgba(245,190,67,.45);border-radius:10px;color:#f5c75b;background:rgba(245,190,67,.08);font-size:12px;letter-spacing:.08em;text-transform:uppercase}.public-cta .ghost-button{margin-top:12px}.auth-panel textarea{resize:vertical}';document.head.appendChild(style);refresh();
})();
