const favicon=document.createElement("link");favicon.rel="icon";favicon.type="image/svg+xml";favicon.href="assets/stataxis-favicon.svg";document.head.appendChild(favicon);const nav='<header class="sx-nav"><div class="sx-nav-inner"><a class="sx-logo" href="/" aria-label="StatAxis home"><img src="assets/stataxis-logo.svg" alt="StatAxis — Stat the View. Axis the Viewpoint."></a><button class="sx-mobile" aria-label="Open menu" aria-expanded="false">☰</button><nav class="sx-menu"><a href="platform.html">Platform</a><a href="solutions.html">Solutions</a><a href="research.html">Research</a><a href="insights.html">Insights</a><a href="stx.html">STX Index</a><a href="stax9.html">STAX9</a><a class="sx-cta" href="mailto:stax9@stataxis.org?subject=StatAxis%20Enquiry">Talk to us</a></nav></div><div class="sx-mobile-menu"><a href="platform.html">Platform</a><a href="solutions.html">Solutions</a><a href="research.html">Research</a><a href="insights.html">Insights</a><a href="stx.html">STX Index</a><a href="stax9.html">STAX9</a><a class="sx-cta" href="mailto:stax9@stataxis.org?subject=StatAxis%20Enquiry">Talk to us</a></div></header>';const footer='<footer class="sx-footer"><div class="sx-footer-inner"><div><strong>STATAXIS</strong><br>Digital Media Market Intelligence & Data Services</div><div><strong>StatAxis Technology Lab</strong><br>Lab-grown website, developed in the State-of-the-Art Technology Data Lab of StatAxis.<br>Built indigenously with our own systems, processes and technology.</div><div class="sx-legal"><strong>Data, Name & Intellectual Property</strong><br>Prior written permission from StatAxis is required before using or mentioning the StatAxis name, logo, data, content or STX Index in any external publication, product, service, campaign or communication.<br>Without our prior written consent, do not use our name, logo, data or STX Index.<br>No production credit is assigned to any third party.<br>STX Index and other scores are generated independently by StatAxis. They are not sourced from, provided by or endorsed by YouTube.</div><div>© 2026 StatAxis.<br>All rights reserved.<br><a href="/privacy.html">Privacy Policy</a> · <a href="/terms.html">Terms & Conditions</a><br><a href="mailto:stax9@stataxis.org">stax9@stataxis.org</a></div></div></footer>';document.getElementById("nav").innerHTML=nav;document.getElementById("footer").innerHTML=footer;const toggle=document.querySelector(".sx-mobile");const mobileMenu=document.querySelector(".sx-mobile-menu");if(toggle&&mobileMenu){toggle.addEventListener("click",()=>{const open=mobileMenu.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));toggle.textContent=open?"×":"☰";});}
const SX_COOKIE_KEY="stataxis_cookie_consent_v1",SX_TERMS_KEY="stataxis_terms_consent_v1";
(function(){
  const style=document.createElement("style");
  style.textContent=".sx-consent{position:fixed;inset:0;z-index:10000;background:rgba(3,10,18,.94);backdrop-filter:blur(14px);display:flex;align-items:center;justify-content:center;padding:22px}.sx-consent-box{width:min(720px,100%);background:#0b1b2b;border:1px solid #304b61;border-radius:18px;padding:30px;box-shadow:0 28px 80px rgba(0,0,0,.65);color:#e8f0f8}.sx-consent-kicker{color:#e1b94f;font-size:11px;font-weight:800;letter-spacing:.12em}.sx-consent h2{font-size:30px;margin:8px 0 10px}.sx-consent p{color:#9bb0c1;line-height:1.65}.sx-consent-section{border:1px solid #20394e;background:#081725;border-radius:12px;padding:15px;margin:14px 0}.sx-consent-section strong{color:#e8f0f8}.sx-consent-check{display:flex;gap:10px;align-items:flex-start;color:#d7e3ec;font-size:13px;margin:15px 0}.sx-consent-check input{accent-color:#e1b94f;margin-top:3px}.sx-consent a{color:#e1b94f}.sx-consent-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.sx-consent button{border:1px solid #31536b;background:#0d2234;color:#e8f0f8;border-radius:8px;padding:11px 16px;font-weight:800;cursor:pointer}.sx-consent button:hover{background:#e1b94f;border-color:#e1b94f;color:#061322}.sx-consent button.primary{background:#159de8;border-color:#159de8}.sx-consent button.primary:disabled{opacity:.45;cursor:not-allowed}.sx-consent button.primary:not(:disabled):hover{background:#e1b94f;border-color:#e1b94f}.sx-consent-note{font-size:11px;color:#70899d}.sx-consent-deny{font-size:12px;color:#ff7885;margin-top:10px}";
  document.head.appendChild(style);
  if(location.pathname.endsWith("/terms.html")||location.pathname.endsWith("terms.html")||location.pathname.endsWith("/privacy.html")||location.pathname.endsWith("privacy.html")) return;
  if(localStorage.getItem(SX_COOKIE_KEY)&&localStorage.getItem(SX_TERMS_KEY)) return;
  document.documentElement.style.overflow="hidden";
  const gate=document.createElement("div");gate.className="sx-consent";gate.innerHTML='<div class="sx-consent-box"><div class="sx-consent-kicker">WELCOME TO STATAXIS</div><h2>Before you enter</h2><p>We use essential cookies to remember consent and basic website preferences. Before continuing, please review and agree to the StatAxis Terms & Conditions.</p><div class="sx-consent-section"><strong>Cookie consent</strong><p class="sx-consent-note">StatAxis currently uses essential consent/preference storage. No non-essential tracking is required to enter this website.</p><div class="sx-consent-actions"><button id="sxEssential">Continue with essential cookies</button><button id="sxAll" class="primary">Accept cookies</button></div></div><div class="sx-consent-section"><strong>Terms & Conditions</strong><p class="sx-consent-note">By entering the website, you acknowledge that website content, data, analysis, branding and the STX Index are protected and subject to StatAxis terms.</p><label class="sx-consent-check"><input id="sxTerms" type="checkbox"> <span>I have read and agree to the <a href="/terms.html" target="_blank" rel="noopener">StatAxis Terms & Conditions</a> and consent to proceed.</span></label></div><button id="sxEnter" class="primary" disabled>Agree & Enter Website</button><div id="sxDeny" class="sx-consent-deny"></div></div>';
  document.body.appendChild(gate);
  let cookieOk=!!localStorage.getItem(SX_COOKIE_KEY);
  const terms=document.getElementById("sxTerms"),enter=document.getElementById("sxEnter"),deny=document.getElementById("sxDeny");
  const update=()=>{enter.disabled=!(cookieOk&&terms.checked)};
  document.getElementById("sxEssential").onclick=()=>{localStorage.setItem(SX_COOKIE_KEY,"essential");cookieOk=true;deny.textContent="Essential cookie consent recorded.";update()};
  document.getElementById("sxAll").onclick=()=>{localStorage.setItem(SX_COOKIE_KEY,"accepted");cookieOk=true;deny.textContent="Cookie consent recorded.";update()};
  terms.onchange=update;
  enter.onclick=()=>{if(!cookieOk||!terms.checked)return;localStorage.setItem(SX_TERMS_KEY,"accepted");gate.remove();document.documentElement.style.overflow=""};
})();